use pyo3::prelude::*;
use std::collections::HashMap;
// use pyo3_polars::PyDataFrame;
use gene_type_stats::wrapper_compute_gene_type_read_dist;
use unmapped::Unmapped;
mod align_stats;
mod fastq_stats;
mod gene_type_stats;
mod gff_parser;
mod reader;
mod star_stats;
mod unmapped;
// mod crosslink_parser; // <-- commenting out for now, as it is not fully working yet

/// parse single end bam file and
/// split unmapped fastqs into two files: (i) all multimappers (ii) other unmapped reads
/// generate unmapped statistics as json
#[pyfunction]
fn single_end_unmapped_fastq(
    bam: &str,
    fq_multi: &str,
    fq_other: &str,
) -> HashMap<String, Unmapped> {
    let unmapped_stat = unmapped::unmapped_writer_single_end(bam, fq_multi, fq_other);
    unmapped_stat
}

/// compute read length count data from input fastq file
/// supports flat file and gz files
#[pyfunction]
fn fastq_read_length(fastq: &str) -> HashMap<u16, u32> {
    fastq_stats::fastq_read_length_counter(fastq)
}

/// parse bam file generated by STAR aligner and output alignment stats
#[pyfunction]
fn star_bam_stats(bam: &str, min_q: u8) -> HashMap<String, u32> {
    star_stats::bam_stats(bam, min_q)
}

/// parse any bam file and generate stats for mapped, unmapped and total reads
#[pyfunction]
fn alignment_stats(bam: &str, min_q: u8) -> HashMap<String, u32> {
    align_stats::alignment_stats(bam, min_q)
}

/// compute gene type read length distribuition
#[pyfunction]
fn gene_type_read_dist(
    bam_file: &str,
    min_q: u8,
    ignore_duplicate: bool,
    gff3_file: &str,
    features: Vec<String>,
    gene_id: String,
    gene_name: String,
    gene_type: String,
) -> HashMap<String, HashMap<u16, u32>> {
    wrapper_compute_gene_type_read_dist(
        bam_file,
        min_q,
        ignore_duplicate,
        gff3_file,
        features,
        gene_id,
        gene_name,
        gene_type,
    )
}

// parse crosslink bed file and generate count data for each crosslink site
// there is very little advantage over using python polars, but massively increases compile time
// #[pyfunction]
// fn crosslink_parser_rs(bed: &str) -> PyResult<PyDataFrame>{
//     let counts = crosslink_parser::parse_crosslinks(bed)
//     .map_err(|e| PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(e.to_string()))?;
//     Ok(pyo3_polars::PyDataFrame(counts))
// }

/// A Python module implemented in Rust.
#[pymodule]
fn statter(_py: Python, m: &Bound<'_, PyModule>) -> PyResult<()> {
    // parse unmapped reads from bam files from single end sequencing
    m.add_function(wrap_pyfunction!(single_end_unmapped_fastq, m)?)?;
    m.add_function(wrap_pyfunction!(star_bam_stats, m)?)?;
    m.add_function(wrap_pyfunction!(alignment_stats, m)?)?;
    m.add_function(wrap_pyfunction!(fastq_read_length, m)?)?;
    m.add_function(wrap_pyfunction!(gene_type_read_dist, m)?)?;
    // m.add_function(wrap_pyfunction!(crosslink_parser_rs, m)?)?;
    Ok(())
}
