# generated by datamodel-codegen:
#   filename:  SLBP_test.json
#   timestamp: 2025-11-02T16:38:55+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Star(BaseModel):
    Input_reads: int = Field(..., alias='Input reads')
    Mapped_Total: int = Field(..., alias='Mapped: Total')
    Mapped_Total_perc: float = Field(..., alias='Mapped: Total %')
    Mapped_Unique_reads: int = Field(..., alias='Mapped: Unique reads')
    Mapped_Unique_reads_perc: float = Field(..., alias='Mapped: Unique reads %')
    Mapped_PCR_duplicate_reads: int = Field(..., alias='Mapped: PCR duplicate reads')
    Mapped_PCR_duplicate_reads_perc: float = Field(
        ..., alias='Mapped: PCR duplicate reads %'
    )
    Mapped_Uniquely_mapped_reads: int = Field(
        ..., alias='Mapped: Uniquely mapped reads'
    )
    Mapped_Uniquely_mapped_reads_perc: float = Field(
        ..., alias='Mapped: Uniquely mapped reads %'
    )
    Mapped_Multimapped_reads: int = Field(..., alias='Mapped: Multimapped reads')
    Mapped_Multimapped_reads_perc: float = Field(..., alias='Mapped: Multimapped reads %')
    Unmapped_Total: int = Field(..., alias='Unmapped: Total')
    Unmapped_Total_perc: float = Field(..., alias='Unmapped: Total %')
    Unmapped_mapped_to_too_many_loci: int = Field(
        ..., alias='Unmapped: mapped to too many loci'
    )
    Unmapped_mapped_to_too_many_loci_perc: float = Field(
        ..., alias='Unmapped: mapped to too many loci %'
    )
    Unmapped_no_seed_windows: int = Field(..., alias='Unmapped: no seed/windows')
    Unmapped_no_seed_windows_perc: float = Field(..., alias='Unmapped: no seed/windows %')
    Unmapped_too_short: int = Field(..., alias='Unmapped: too short')
    Unmapped_too_short_perc: float = Field(..., alias='Unmapped: too short %')
