use pyo3::prelude::*;
use std::collections::HashMap;
use unmapped::Unmapped;
mod unmapped;
mod star_stats;
/// parse single end bam file and
/// split unmapped fastqs into two files: (i) all multimappers (ii) other unmapped reads
/// generate unmapped statistics as json
#[pyfunction]
fn single_end_unmapped_fastq(bam: &str, fq_multi: &str, fq_other: &str) -> HashMap<String, Unmapped>{
    let unmapped_stat = unmapped::unmapped_writer_single_end(bam, fq_multi, fq_other);
    unmapped_stat
}

/// parse bam file generated by STAR aligner and output alignment stats
#[pyfunction]
fn star_bam_stats(bam: &str, min_q: u8) -> HashMap<String,u32>{
    star_stats::bam_stats(bam, min_q)
}
/// A Python module implemented in Rust.
#[pymodule]
fn statter(_py: Python, m: &PyModule) -> PyResult<()> {
    // parse unmapped reads from bam files from single end sequencing
    m.add_function(wrap_pyfunction!(single_end_unmapped_fastq, m)?)?;
    m.add_function(wrap_pyfunction!(star_bam_stats, m)?)?;
    Ok(())
}

