# generated by datamodel-codegen:
#   filename:  fastp.json
#   timestamp: 2025-11-02T16:56:05+00:00
#  This file has been manually edited to make read2 stats and insert size optional.

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


class BeforeFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q20_rate: float
    # q30_rate: float
    read1_mean_length: int
    read2_mean_length: Optional[int] = None
    gc_content: float


class AfterFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q20_rate: float
    # q30_rate: float
    read1_mean_length: int
    read2_mean_length: Optional[int] = None
    gc_content: float

class Summary(BaseModel):
    fastp_version: str
    sequencing: str
    before_filtering: BeforeFiltering
    after_filtering: AfterFiltering

class FilteringResult(BaseModel):
    passed_filter_reads: int
    low_quality_reads: int
    too_many_N_reads: int
    too_short_reads: int
    too_long_reads: int

class Duplication(BaseModel):
    rate: float

class InsertSize(BaseModel):
    peak: int
    unknown: int
    histogram: List[int]

class AdapterCutting(BaseModel):
    adapter_trimmed_reads: int
    adapter_trimmed_bases: int
    read1_adapter_sequence: str
    read2_adapter_sequence: Optional[str] = None
    read1_adapter_counts: Dict[str,int]
    read2_adapter_counts: Optional[Dict[str,int]] = None

class QualityCurves(BaseModel):
    A: List[float]
    T: List[float]
    C: List[float]
    G: List[float]
    mean: List[float]

class ContentCurves(BaseModel):
    A: List[float]
    T: List[float]
    C: List[float]
    G: List[float]
    N: List[float]
    GC: List[float]

class Read1BeforeFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q40_bases: int
    total_cycles: int
    quality_curves: QualityCurves
    content_curves: ContentCurves
    kmer_count: Dict[str, int]
    overrepresented_sequences: Dict[str, Any]

class Read2BeforeFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q40_bases: int
    total_cycles: int
    quality_curves: QualityCurves
    content_curves: ContentCurves
    kmer_count: Dict[str, int]
    overrepresented_sequences: Dict[str, Any]

class Read1AfterFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q40_bases: int
    total_cycles: int
    quality_curves: QualityCurves
    content_curves: ContentCurves
    kmer_count: Dict[str, int]
    overrepresented_sequences: Dict[str, Any]

class Read2AfterFiltering(BaseModel):
    total_reads: int
    total_bases: int
    # q20_bases: int
    # q30_bases: int
    # q40_bases: int
    total_cycles: int
    quality_curves: QualityCurves
    content_curves: ContentCurves
    kmer_count: Dict[str, int]
    overrepresented_sequences: Dict[str, Any]

class Fastp(BaseModel):
    model_config = ConfigDict(extra='allow')  # Allow extra fields
    
    summary: Summary
    filtering_result: FilteringResult
    duplication: Duplication
    insert_size: Optional[InsertSize] = None
    adapter_cutting: AdapterCutting
    read1_before_filtering: Read1BeforeFiltering
    read2_before_filtering: Optional[Read2BeforeFiltering] = None
    read1_after_filtering: Read1AfterFiltering
    read2_after_filtering: Optional[Read2AfterFiltering] = None
    command: str 
