name: Builder
# This workflow build on quay.io/pypa/manylinux_2_28_x86_64 image, which has glibc 2.28, compatible with most distros
on:
    release:
        types: [published]

jobs:
    release-build:
        runs-on: ubuntu-latest
        container:
            image: quay.io/pypa/manylinux_2_28_x86_64
        outputs:
            wheel: dist/*.whl
        steps:
            -   name: dependencies
                run: |
                    dnf install -y perl-IPC-Cmd
                    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: build
                run: |
                    source $HOME/.cargo/env
                    uv sync --group build
                    uv run maturin build --release --out dist
            -   name: Upload wheels
                uses: actions/upload-artifact@v4
                with:
                    name: wheels
                    path: dist/*.whl
    
    publish-pypi:
        name: publish to PyPI
        needs: release-build
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write
        steps:
            -   name: Download wheels
                uses: actions/download-artifact@v4
                with:
                    name: wheels
                    path: dist/
            -   name: release to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    packages-dir: dist/
            
