name: CI

on:
  release:
    types: [published]

permissions:
  contents: read

# this workflow is disabled,
# uses the latest glibc version (2.38) on ubuntu-latest, which is not compatible with some distros
jobs:
  if: false
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: setup python
        run: uv python install
      - name: install dependencies
        run: uv sync
      - name: build
        run: uvx maturin build --release --out dist
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*.whl
  
  publish-pypi:
    name: publish to PyPI
    needs: release-build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/
      - name: release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
